# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('disklike', '左滑'), ('like', '右滑'), ('superlike', '上滑')], max_length=16, verbose_name='滑动类型')),
                ('uid', models.IntegerField(verbose_name='滑动者的 uid')),
                ('sid', models.IntegerField(verbose_name='被滑动者的 uid')),
                ('stime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
